//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesDatabase_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameReleaseDateDatabaseEntities6 : DbContext
    {
        public GameReleaseDateDatabaseEntities6()
            : base("name=GameReleaseDateDatabaseEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<gameGenre> gameGenres { get; set; }
        public virtual DbSet<gamePlatform> gamePlatforms { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<platform> platforms { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
